/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package io.restall.picodi.example

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App(mavenService)

        when:
        def result = app.greeting

        then:
        result != null
    }
}
